version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: alexeynl/zoneminder:latest
        restart: unless-stopped
        ports:
            - 7878:80
        #network_mode: "bridge" #optional
        privileged: true
        shm_size: 512M
        environment:
            - TZ=${TZ:-Europe/Moscow}
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - config:/config
            - events:/var/cache/zoneminder/events
            - images:/var/cache/zoneminder/images
            - mysql:/var/lib/mysql
            - logs:/var/log/zoneminder
volumes:
  config:
  events:
  images:
  mysql:
  logs:
